### ISSUE TITLE
Unable to provision an Autonomous database

### ISSUE THREAD

**Issue by namishra2020** [oracle/learning-library#1043]
Hi,

I am unable to an provision an Autonomous Transaction database at 
https://console.us-ashburn-1.oraclecloud.com 
Username : user37

It fails with the below error 
Operation Create Autonomous Database failed, contact Oracle Support with work request: e22d1cf4-3901-4702-b7ab-8495922b2195 , job id: 90fc3b0f-70bb-47ed-896f-03d6269c5081 and message Database job: Failed. Error: atp_pdb.pm: create: PDB Placement failed.

Please look into it

Regards,

Navnit

**Comment by tmcginn** [comment]
Navnit,
Please reach out to Oracle Support: https://support.oracle.com/portal/
Thanks
