### ISSUE TITLE
Cannot DROP or ALTER cloud credential 'DBMS_CLOUD.create_credential'

### ISSUE THREAD

**Issue by ksoni5** [oracle/learning-library#1044]
I Accidentally entered wrong password while creating credential 'DBMS_CLOUD.create_credential'

Now I want to drop or alter the credential but the commands are throwing error 'Unknown command'

DBMS_CREDENTIAL.DROP_CREDENTIAL (
   OBJ_STORE_CRED   IN  VARCHAR);

Can anyone suggest me what should I do?

**Comment by tmcginn** [comment]
I believe you need to use DBMS_CLOUD.drop_credential. See https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/dbms-cloud.html#GUID-7373D043-C3AE-4D86-87BE-4F7ACC8B3EB5 for details.

**Comment by ksoni5** [comment]
Oh thanks for pointing out, I did check that page but didn't notice the difference. Also, I had to remove VARCHAR2 to run it successfully. I used below query exactly:

```
set define off
begin
  DBMS_CLOUD.DROP_CREDENTIAL(
    OBJ_STORE_CRED
  );
end;
/
set define on
```
