### ISSUE TITLE
Summary for the Reserved Public IP lab is wrong

### ISSUE THREAD

**Issue by Djelibeybi** [oracle/learning-library#1045]
Hey folks,

This was pointed out to me via email from a friendly user via email.

The content in the summary section of https://github.com/oracle/learning-library/blob/master/oci-library/L100-LAB/Using_Reserved_Public_IP/Reserved_Public_IP_HOL.md is wrong. It's talking about storage in a Public IP lab.

Could the responsible person please take a look at fix it up as necessary?

Thanks,
Avi

**Comment by umairs123** [comment]
This lab repo is not the one used, i will ask Flavio to disable it. Correct lab is @ https://github.com/oracle/learning-library/tree/master/oci-library/qloudable/Using_Reserved_Public_IP

**Comment by flavio-santino** [comment]
I fixed the lab described above. Closing this issue.
