### ISSUE TITLE
Unable to load data from the Object Storage using DBMS_CLOUD; getting 'Authorization failed for URI' error

### ISSUE THREAD

**Issue by ksoni5** [oracle/learning-library#1047]
I am trying to load data object from Object Storage using DBMS cloud and writing below query. I've checked, the url is correct, but I am getting authorization error:

If there's nothing to change in the below query, then is there a way to check the User I generated the auth token for is admin or not?

Below is my query and the error I am seeing:

```
define base_URL='https://swiftobjectstorage.ca-toronto-1.oraclecloud.com/v1/ksoni5/Lab2ATP'

define customer_dat_URL = '&base_URL/customers.csv';

begin
 dbms_cloud.copy_data(
    table_name =>'CUSTOMERS',
    credential_name =>'OBJ_STORE_CRED',
    file_uri_list => '&customer_dat_URL',
    format => json_object('ignoremissingcolumns' value 'true', 'removequotes' value 'true', 'dateformat' value 'YYYY-MM-DD HH24:MI:SS', 'blankasnull' value 'true')
 );
end;
/
```

I am getting error :

> Error report -
> ORA-20401: Authorization failed for URI - https://swiftobjectstorage.ca-toronto-1.oraclecloud.com/v1/ksoni5/Lab2ATP/customers.csv
> ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 759
> ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 1642
> ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 1665
> ORA-06512: at line 2

**Comment by DanielCasM** [comment]
Hello! Did you solve it?

**Comment by ksoni5** [comment]
Hello!

Yes! I could. I tried to [delete the credentials](https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/user/dbms-cloud.html#GUID-7373D043-C3AE-4D86-87BE-4F7ACC8B3EB5) and then regenerate them. I made a mistake of using another password instead of the token generated. I just had to go few steps back and start again.

**Comment by jasperan** [comment]
Update for people that may be encountering this error: make sure that the username you specify in the credentials, if you are connecting to your OCI account, has the full name. For example, my name would be 'oraclecloudidentityservice/jasperan' since my credentials are generated by the IDCS.

**Comment by jamescgonzales** [comment]
> Update for people that may be encountering this error: make sure that the username you specify in the credentials, if you are connecting to your OCI account, has the full name. For example, my name would be 'oraclecloudidentityservice/jasperan' since my credentials are generated by the IDCS.

This worked for me.

**Comment by DavidVelasco1982** [comment]
Hi All, 
Related to James Gonzales Response. I had my mail for the username = 'oraclecloudidentityservice/xx.xx00@gmail.com'
I found the same error. So Maybe I never thought that the username has to be shorter.
I have to create another Oracle Cloud Account and Reapeat everything from the 1st step?
Best regards from Mexico. Can you help me, please.

**Comment by jasperan** [comment]
Hello @DavidVelasco1982, just make sure that the username with which you login into your OCI tenant is exactly the same. If it is generated manually, for example, you generate a new user from the console, then the username should be something like 'xx.xx00@gmail.com', but if it has been created by Oracle's Identity Cloud Service, it should be something like 'oraclecloudidentityservice/xx.xx00@gmail.com'. 

You can message me or mention me if you keep having trouble with this.
