### ISSUE TITLE
Deploying APM Agent and setting up Application Performance Monitoring

### ISSUE THREAD

**Issue by avishayx** [oracle/learning-library#106]
https://oracle.github.io/learning-library/workshops/chefjenkins-devops/

AgentInstall.zip was no longer appear in OMC.

Could you please if there is any alternative for that?
It seems i couldn't find a way to APM my DevCs env, didn't find any relevant pom file in OMC.

Please advise.

Thank you for the great Job you did here.

**Comment by kaymalcolm** [comment]
Closing.  Old issue.
