### ISSUE TITLE
While trying to compute instance following Oracle learning path, getting out of capacity error

### ISSUE THREAD

**Issue by ksoni5** [oracle/learning-library#1077]
I am following a [learning path](https://apexapps.oracle.com/pls/apex/f?p=44785:52:8092604046361::NO:RP::)

Problem: While on **Step 2 "Provision a linux compute VM to serve as the app server"**, we have to create a Compute Instance. The region I selected while creating account was 'Canada Southeast Toronto'.

**Error:**

> Out of capacity for shape VM.Standard.E2.1.Micro in availability domain pUbC:CA-TORONTO-1-AD-1. Please try again later.

Can anyone please suggest something?

**Comment by kaymalcolm** [comment]
Try another availability domain or shape.  Each tenancy has policy limits based on shape, region and availability domain.
