### ISSUE TITLE
# Bike Share Demand Prediction Workshop

### ISSUE THREAD

**Issue by pdadwal** [oracle/learning-library#1100]
Hello Team,

While following Lab500 at link "https://oracle.github.io/learning-library/workshops/bike-share-prediction/?lab=workshop-introduction", Facing challenge in completing the Part 1 of Lab500 as listed below:
"In the Notebooks section, click on Import and import the [Bike Share Availability Prediction.json](./files/scripts/Bike Share Availability Prediction.json) file."

This Bike Share Availability prediction.json file is missing in the lab and hence unable to complete the lab.

Pls address this issue on urgent basis or let me know the exact path from where this file .json can be downloaded.

Thanks,
Pardeep

**Comment by snicholspa** [comment]
Hello, it appears the file is there and located in the following location - https://github.com/oracle/learning-library/blob/master/workshops/bike-share-prediction/files/scripts/Bike%20Share%20Availability%20Prediction.json

Steve

**Comment by kaymalcolm** [comment]
Closing issue.  It appears to be resolved.
