### ISSUE TITLE
package.js and npm install steps missing

### ISSUE THREAD

**Issue by vmleon** [oracle/learning-library#1124]
On **Lab 5: Configure node.js app with ATP** the zip file [ATPnodeapp.zip](https://github.com/oracle/learning-library/blob/master/workshops/autonomous-transaction-processing/scripts/500/ATPnodeapp.zip?raw=true) with the node application folder doesn't contain `package.json`. There is no step to install dependencies like `npm install`.

Workaround:
```
npm init -y
npm install oracledb
```

**Comment by kaymalcolm** [comment]
@vmleon can you provide the path to the lab please?

**Comment by kaymalcolm** [comment]
Closing. No response from participant.
