### ISSUE TITLE
ATP Dedicate Workshop Lab 2 - Provisioning Exadata Infrastructure - Port 22 not enabled

### ISSUE THREAD

**Issue by oscrub** [oracle/learning-library#1132]
Going through the steps described to create an Autonomous Exadata Infrastructure. After filling in the details as described in the lab, when clicking the button to create the infrastructure I get the message: 

"Request is rejected as port 22 is not enabled in the security list for subnet ocid1.subnet.oc1.xxxx..."

I've configured the subnet security list as described in the previous lab, and have also tried specifically allowing port 22 similar to Doc ID 2433870.1, but still get the same error. 

Also doing the lab in my OCI Free Tier account, haven't had a chance to test in the ACS Lab yet.

**Comment by kaymalcolm** [comment]
@kbhanush @tejuscs can you take a look?

**Comment by oscrub** [comment]
Hi Kay, I was able to resolve it. It requires 2 additional egress rules not mentioned in the lab guide: 
1. ssh/22 to all IPs, and 
2. all traffic for all ports to the exa subnet, 10.0.0.0/24. 
Though I then hit an error regarding service limits on creating the dedicated Exa, but that's a different issue altogether :) Thanks
