### ISSUE TITLE
dead link in Oracle APEX Hands-On Lab

### ISSUE THREAD

**Issue by soumunote** [oracle/learning-library#1144]
There's dead link in [Oracle APEX Hands-On Lab (Existing Tables Module 
2)](https://github.com/oracle/learning-library/blob/master/developer-library/apex/existing-tables/2-installing-sample-tables.md)

In SUMMARY Section "Click here to navigate to Module 3"
Please change from
https://github.com/oracle/learning-library/blob/master/developer-library/apex/existing-tables/3-create-the-app.md
to
https://github.com/oracle/learning-library/blob/master/developer-library/apex/existing-tables/3-create-app.md

Thank you.

**Comment by kaymalcolm** [comment]
@tmcginn or @apex-dpeake could you take a look at this?  I think Tom's update may have fixed this.

**Comment by tmcginn** [comment]
Fixed the broken link.
