### ISSUE TITLE
Insufficient privileges

### ISSUE THREAD

**Issue by Jeevanhm** [oracle/learning-library#1167]
I'm getting error while executing pl/sql procedure as admin user.

Error report -
ORA-27486: insufficient privileges
ORA-06512: at "SYS.DBMS_CREDENTIAL", line 44
ORA-06512: at "SYS.DBMS_ISCHED", line 3472
ORA-06512: at "SYS.DBMS_CREDENTIAL", line 32

**Comment by kaymalcolm** [comment]
@Jeevanhm please provide the link to the workshop you are using

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
