### ISSUE TITLE
Oracle Cloud Hands-on Labs GitHub Autonomous Data Warehouse

### ISSUE THREAD

**Issue by BruninkJ** [oracle/learning-library#1259]
Following the hands on labs for creating an autonomous datawarehouse

Under 

> Practice 1: Download channel text file and install SQL Developer Tool

It says 

> 1. Download a zip file from this link: http://bit.ly/2yOzzVE and save it to your desktop.

Clicking the link gives following error

[{"code":"BucketNotFound","message":"Either the bucket named 'OCI-Training' does not exist in the namespace 'bmc-flaviop' or you are not authorized to access it"}](url)

**Comment by williamabarca01** [comment]
Hello all,
Same error:
![image](https://user-images.githubusercontent.com/13476555/80896595-5914fd00-8cad-11ea-8ce6-1062dbdaab5a.png)

**Comment by svenschuldt** [comment]
Same error on my side - anybody looking into this?

**Comment by anooshapilli** [comment]
Hi guys, can you please provide the link to the workshop you are using?

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.

**Comment by aazayka** [comment]
Still an issue

**Comment by tmcginn** [comment]
Ok, I still need to know which workshop

**Comment by aazayka** [comment]
**[Autonomous Data Warehouse](https://oracle.github.io/learning-library/oci-library/L100-LAB/Autonomous_Data_Warehouse/ADW_HOL.html)** 

Link in 

> Download a zip file from this link: http://bit.ly/2yOzzVE and save it to your desktop.  

is not working
