### ISSUE TITLE
typo on video link text

### ISSUE THREAD

**Issue by jtsaismith** [oracle/learning-library#1296]
On this page https://github.com/oracle/learning-library/tree/master/data-management-library/database/developers, the link to the video at the bottom of the page contains a typo. Instead of "by" it should be "my."

**Comment by kaymalcolm** [comment]
Thanks for catching that Jenny.  @anooshapilli please fix this.

**Comment by kaymalcolm** [comment]
@jtsaismith this is fixed.  Closing this issue.
