### ISSUE TITLE
Wrong Module Text in APEX Hands-On Lab Building an App from a Spreadsheet 

### ISSUE THREAD

**Issue by Berend-de-Vries** [oracle/learning-library#1301]
Oracle APEX Hands-On Lab
Building an App from a Spreadsheet for Oracle Autonomous Cloud Service
Module 5.
https://oracle.github.io/learning-library/developer-library/apex/spreadsheet/?page=5-linking-the-calendar.md
A: In this module instructions are to edit Page 7. This should be Page 6
B: Dynamic Link should be to page 5 (and not to Page 4). Also 4's should be replaced by 5's in de Dynamic Link Specofocation

**Comment by anooshapilli** [comment]
@Berend-de-Vries I am looking into it.

**Comment by apex-dpeake** [comment]
@Berend-de-Vries Thank you for reporting this issue. It is a change in behavior introduced with APEX 20.1 that by default it also creates a form page for Faceted Searches. For APEX 20.2 that change will be reverted back, as it is confusing to have two form pages. 
Regards,
David Peake
