### ISSUE TITLE
Where is the Data?

### ISSUE THREAD

**Issue by aminadatia** [oracle/learning-library#1327]
Where do I get the Data from?

select * from user_mining_models;

returns nothing

**Comment by troyanthony06** [comment]
What workshop are you running?

**Comment by aminadatia** [comment]
The AI and Machine Learning with Wine selection data


Regards
Amin Adatia
613-864-8378

________________________________

**Comment by anooshapilli** [comment]
Can you please provide the link to the lab?

**Comment by aminadatia** [comment]
This is where I started from ..

https://blogs.oracle.com/machinelearning/hands-0n-lab%3a-how-to-pick-a-good-wine-for-30%3c-using-oracle-autonomous-database%2c-oracle-machine-learning%2c-apex%2c-oracle-analytics-cloud-and-rest-services


Regards


Amin Adatia
613-864-8378

________________________________

**Comment by tmcginn** [comment]
Hi Amin,

Assuming you are following the blog, you should look at this paragraph: 
Note: Original data comes from Kaggle WineReviews130K data = 130k wine reviews with variety, location, winery, price, and description etc. Wine Reviews and Twitter Handle were removed. Points was binned to GT_90 and LT_90 https://www.kaggle.com/zynicide/wine-reviews

If you'd like to run the workshop created from the blog, you can find it here: https://ocitraining.qloudable.com/lab/782c8229-d07c-412a-be62-99cf477d9018

Alternatively, we offer a free lab on Oracle Machine Learning here: https://oracle.github.io/learning-library/data-management-library/oracle-machine-learning/adb-oml/workshop/
