### ISSUE TITLE
Lab 3:Migrate ML Model to ATP

### ISSUE THREAD

**Issue by 5009971ontarioltd** [oracle/learning-library#1335]
In the Lab 3:Migrate ML Model to ATP, under section "Step 2: Export the machine learning model", #4 select * from user_mining_models;  returns no records indicating that the  machine learning model was not built.
I am in the Oracle Machine Learning on Autonomous Database Workshop and followed all steps as mentioned in Lab 1: Create Machine Learning Model. 
I am new to Machine learning so would request guidance to resolve this and progress with the lab.
![Lab 3 issue](https://user-images.githubusercontent.com/65271260/81772265-6dc67180-94b3-11ea-97e9-6a71694782a5.jpg)

**Comment by anooshapilli** [comment]
Hi, I am aware of this issue. Working on the fix. I will update you once I push the changes for this workshop.

**Comment by anooshapilli** [comment]
@kaymalcolm - can close this issue.
