### ISSUE TITLE
Error while creating Module in Oracle Machine Learning with Autonomous Database Workshop

### ISSUE THREAD

**Issue by 5009971ontarioltd** [oracle/learning-library#1344]
Workshop name = Oracle Machine Learning with Autonomous Database Workshop
Lab name = Lab 4: Using Prediction in an Application
Error encountered at Step 4: Expose the ml model as a REST end point so any application can call it.
Error message received = ORA-20012: Schema not REST enabled : ML_USER

Screenshot below:

![Error in Module creation](https://user-images.githubusercontent.com/65271260/82098862-d12eea00-96d3-11ea-851c-ba20ef731aa8.jpg)

**Comment by anooshapilli** [comment]
@dgcameron can you help to fix this issue?

**Comment by 5009971ontarioltd** [comment]
I was able to fix this by registering the schema to ORDS and completed the workshop.
So closing the issue.

![Register Schema with ORDS](https://user-images.githubusercontent.com/65271260/82514609-2e67d880-9ae4-11ea-85af-39d57081e912.jpg)
