### ISSUE TITLE
Where is the ADB Lab (Data) 1 to 11. 

### ISSUE THREAD

**Issue by gupraj** [oracle/learning-library#1345]
Hello,
Can you please help me to get ADB lab listed below. Please suggest.

https://github.com/oracle/learning-library/blob/master/data-management-library/autonomous-database/shared/adb-advanced-workshop/intro.md

Lab 1: Log in to Oracle Cloud and access the Oracle Autonomous Data Warehouse console.
Lab 2: Provision your first Autonomous Data Warehouse.
Lab 3: Explore the provided sample data sets that come with your Autonomous Database.
Lab 4: Upload files to the Oracle Cloud Infrastructure (OCI) Object Storage, create sample tables, load data into them from files on the OCI Object Storage, and troubleshoot data loads with errors.
Lab 5: Query files on the Oracle Cloud Infrastructure Object Storage (OCI) directly without loading them to your database.
Lab 6: Visualize your data using Oracle Analytics Desktop.
Lab 7: Use wallets for secure connections to the autonomous database.
Lab 8: Manage and monitor your autonomous Database.
Lab 9: Scale up your Oracle Autonomous Database service to have more CPUs.
Lab 10: Create Oracle Machine Learning SQL notebooks.
Lab 11: Use the in-database DBMS_PREDICTIVE_ANALYTICS functionality.

**Comment by gupraj** [comment]
@nilaypanchal Can you please help me to get lab details data..

Thanks.

**Comment by troyanthony06** [comment]
The labs can be accessed via the LiveLabs page:
https://apex.oraclecorp.com/pls/apex/f?p=LIVELABS:13:115904037639370:::::

The one you refer to above is "Autonomous Database in Depth"
