### ISSUE TITLE
Develop Python with ATP-Lab:1 Setup Step:6 Issue in Loading Data using Sql Developer

### ISSUE THREAD

**Issue by M-FAREED** [oracle/learning-library#1355]
I Went through the workshop Dvelop Python with ATM lab1 till step 6: SQL Developer and Load Data into userid Alpha and found an errors detailed below.

**ORA-39001: invalid argument value ORA-06512: at line 39 ORA-06512: at "SYS.DBMS_SYS_ERROR", line 79 ORA-06512: at "SYS.DBMS_DATAPUMP", line 4929 ORA-06512: at "SYS.DBMS_DATAPUMP", line 5180 ORA-06512: at line 21**

Before this step everything was going fine without any error. Can you please help me to complete the workshop.

Thanks

**Comment by anooshapilli** [comment]
@dgcameron - Can you please help Fareed fix the issue.

**Comment by M-FAREED** [comment]
> @dgcameron - Can you please help Fareed fix the issue.

I found the solution.
