### ISSUE TITLE
Terraform Apply fails for DB19c workshop for JSON

### ISSUE THREAD

**Issue by BXK20** [oracle/learning-library#1356]
After creating a stack, running the terraform apply, I am getting the error, related to version inconsistency and compute instance fails to create. See the error snippet in the attachment. 

[Stack Terraform Apply Error - DB19c Workshop.docx](https://github.com/oracle/learning-library/files/4662886/Stack.Terraform.Apply.Error.-.DB19c.Workshop.docx)

**Comment by anooshapilli** [comment]
@BXK20 Can you please provide me your oracle email? We can chat over slack and get it resolved.

**Comment by BXK20** [comment]
Hello,
My oracle email is bajrang_kundalia@cssus.com.

Please let me know, when you have time to look at my issue. Thanks
Bajrang

**Comment by tmcginn** [comment]
@anooshapilli - did you get a chance to resolve this issue?

**Comment by anooshapilli** [comment]
Hi Bajrang,

Could you please try to run it again. Let us know if you encounter this issue again with your Oracle email. Closing this issue for now.

Thanks,
Anoosha
