### ISSUE TITLE
Create Users fails on front end - helidon

### ISSUE THREAD

**Issue by BXK20** [oracle/learning-library#1357]
In the lab exercise for the microservices for converged database, in the veggie's front end helidon page, when clicking the create users, I am getting SQL error  in the results. Please see the snippet of the error attached. Thanks
![Veggies Helidon Front End SQL Error](https://user-images.githubusercontent.com/64117274/82592641-37ea5280-9b6f-11ea-887c-370e6ef502d1.PNG)

**Comment by tmcginn** [comment]
Thanks for the feedback!
From the author of the lab:

It has to do with password format used.
The customer can either use a password without symbols, eg “Welcome12345” 
or 
1. replace the ATPAQAdminResource.java with the one attached 
[ATPAQAdminResource.zip](https://github.com/oracle/learning-library/files/4664550/ATPAQAdminResource.zip)
2. cd to atpaqadmin directory and run ./build.sh 
3. run `deletepod admin`
4. try again

**Comment by tmcginn** [comment]
If this is still an issue, please reopen it.
