### ISSUE TITLE
Issue loading ML Notebook in Oracle ADW Lab 200 

### ISSUE THREAD

**Issue by adratch** [oracle/learning-library#1359]
<img width="402" alt="Annotation 2020-05-21 164506" src="https://user-images.githubusercontent.com/65736779/82604553-7dfce180-9b82-11ea-8975-e4b48a8f37a0.png">

**Comment by anooshapilli** [comment]
Hi, Can you please provide the link to the lab?

**Comment by adratch** [comment]
Hi Anoosha,

 

Sure it is included below:

 

https://amnisia.github.io/oracle-cloud-data-platform-workshop/?lab=workshop-overview#Introduction

 

Thanks,

 

-Andy

 


Andy Dratch | Cloud Account Manager
Office: HYPERLINK "tel:+1%207817440685"+1 7817440685 | Mobile: HYPERLINK "tel:+1%206039303374"+1 6039303374 | HYPERLINK "https://www.linkedin.com/in/andydratch"LinkedIn

**Comment by tmcginn** [comment]
Hi @adratch - that may be a working copy in someone's fork. Our release/production version of this lab is here: https://oracle.github.io/learning-library/solutions-library/cloud-data-platform/freetier/index.html
Please try that lab and let me know if you get the same error by opening a new issue. Thanks.
