### ISSUE TITLE
Python Development on ATP - Create Stack with sample python4atp.zip with max size 11MB

### ISSUE THREAD

**Issue by lucyhustaty** [oracle/learning-library#1365]
Hello,

during upload a zip file (provided just zipped python4atp.zip ) in Lab 1: Setup, issue with size, zip file is bigger as allowed size 11MB.

Can't continue with the lab.

BR, 
Lucia

**Comment by anooshapilli** [comment]
@dgcameron - can you help Lucy fix the issue.

**Comment by dgcameron** [comment]
lucy that would be my mistake.  I've replaced the file - it's now only 4.7mb.  Should work

**Comment by troyanthony06** [comment]
Making the assumption the fix worked.
