### ISSUE TITLE
Build Error in HOL5769 - Gigi's Pizza

### ISSUE THREAD

**Issue by BXK20** [oracle/learning-library#1366]
I am getting build error when doing HOL for Gigi's pizza workshop. Build Error says:

[2020-05-25 15:04:43] + docker pull store/oracle/database-instantclient:12.2.0.1
[2020-05-25 15:04:43] Error response from daemon: pull access denied for store/oracle/database-instantclient, repository does not exist or may require 'docker login'

Build log is attached. 

My OCIR does not have any images, Is there a step to load images first ? What docker is trying to pull here ?

Thanks

[ms_order_docker_create-199-log.txt](https://github.com/oracle/learning-library/files/4677845/ms_order_docker_create-199-log.txt)

**Comment by anooshapilli** [comment]
Hi, Please try these steps:

ms_order_docker_create job first step is a dockerhub connection to deploy next docker image store/oracle/database-instantclient:12.2.0.1. You must have a dockerhub account (it's free) to download that docker image.

1. Put your dockerhub credentials (suername & password) in the docker login first step.
2. Second step might be a script shell with this commands:

docker pull store/oracle/database-instantclient:12.2.0.1
docker logout

**Comment by tmcginn** [comment]
@anooshapilli - can I close this issue?

**Comment by anooshapilli** [comment]
@tmcginn - yes, can close this issue.
