### ISSUE TITLE
Error in Resource Manager Apply Job

### ISSUE THREAD

**Issue by mzm83** [oracle/learning-library#1369]
Hello,

I have downloaded the "Python Development on ATP" terraform execution script and tried to run.
I have the following error from apply job log:

null_resource.remote-exec (remote-exec): chmod: cannot access ‘/tmp/lab-resources/*.sh’: No such file or directory
null_resource.remote-exec (remote-exec): /tmp/terraform_807318559.sh: line 3: /tmp/lab-resources/ocd_vnc_server.sh: No such file or directory

Please help.

**Comment by anooshapilli** [comment]
Can you please provide the link to the workshop?

**Comment by tmcginn** [comment]
@anooshapilli - I believe it is this one: https://oracle.github.io/learning-library/developer-library/python-on-atp/workshop/?lab=lab-1-setup

**Comment by tmcginn** [comment]
@anooshapilli - can I close this issue?

**Comment by anooshapilli** [comment]
@dgcameron - Could you please help fix this issue.

**Comment by tmcginn** [comment]
Closing this issue, please reopen if needed.
