### ISSUE TITLE
Resource Manager Demo: Plan fails with Error: Missing key/value separator

### ISSUE THREAD

**Issue by stefankoser** [oracle/learning-library#1374]
Uploaded orm-lbass-demo.zip to Resource Manager Stack and executed Plan job
Error occurs only with TF 0.12 - likely because min and max of tcp_options are enclosed in quotes

Error: Missing key/value separator
  on network.tf line 86, in resource "oci_core_security_list" "lb-securitylist" 
  82: 
  83: 
  84: 
  86:       tcp_options {
Expected an equals sign (=) to mark the beginning of the attribute value.

**Comment by anooshapilli** [comment]
Hi Stefan, Could you please provide the link to the lab?

**Comment by stefankoser** [comment]
https://github.com/oracle/learning-library/tree/master/oci-library/DevOps/Resource_Manager/orm-lbaas-demo

**Comment by tmcginn** [comment]
@flavio-santino - can you take a look? 
This is the content in question (in network.tf)

  ingress_security_rules = [
    {
      protocol = "${local.tcp_protocol}"
      source = "${local.anywhere}"

      tcp_options {
        "min" = "${var.non_ssl_listener_port}"
        "max" = "${var.non_ssl_listener_port}"
      }
    },

**Comment by tmcginn** [comment]
@umairs123 - can you take a look?

**Comment by tmcginn** [comment]
Closed due to the age of issue.
