### ISSUE TITLE
Oracle docker live lab email was missing the Image id

### ISSUE THREAD

**Issue by Joel9889** [oracle/learning-library#1376]
I requested the database docker live lab and got the mail saying i still had an account but i could not complete the activity because there is meant to be an Image id in lab 3 that is entered to create the required stack but the mail did not have it.

This was in the mail:

LIVELAB INSTRUCTIONS (START HERE!!!!): https://oracle.github.io/learning-library/data-management-library/database/docker/create-database-in-docker/ssworkshop/

Compartment: dboptionsUSERS
Region: Ashburn
Region Subnet ID(Ashburn): ocid1.subnet.oc1.iad.aaaaaaaayuldua2avhqunlbynab3hjcrflq2x44vzhe25py4v52azvkxoaka
Tenancy: c4u03

**Comment by anooshapilli** [comment]
Hi Joel,

The labs are being updated. 

Could you please use the below Image ID for Ashburn - ocid1.image.oc1.iad.aaaaaaaa6tp7lhyrcokdtf7vrbmxyp2pctgg4uxvt4jz4vc47qoc2ec4anha

Let me know if this helps.

Thanks!

**Comment by tmcginn** [comment]
@anooshapilli - let me know when I can close this issue - thanks!

**Comment by anooshapilli** [comment]
@tmcginn - yes, we can close this issue.
