### ISSUE TITLE
Create an Oracle Database in a Docker Container on Oracle Cloud - Lab7 fails to load

### ISSUE THREAD

**Issue by kswamyna** [oracle/learning-library#1390]
Workshop Name: Create an Oracle Database in a Docker Container on Oracle Cloud
Lab: Lab 7: Add an Ingress Rule to your VCN

When I click the Lab 7 link in the right side panel it fails with following message...

"https://raw.githubusercontent.com/oracle/learning-library/master/data-management-library/database/oci-vm-database/connect-oci-vm-db-sqldeveloper/add-ingress-rule/add-ingress-rule.md not found! Please check that the file is available in the location provided in the manifest file."

**Comment by tmcginn** [comment]
Hi there -
Sorry about that - this issue is now fixed.
Tom
