### ISSUE TITLE
Download the completed application error

### ISSUE THREAD

**Issue by jegyed50** [oracle/learning-library#1416]
HOL: Building an App using a Remote Data Source for Oracle Autonomous Cloud Services
The response to clicking on the link is HTTP 404, File not found.
Click here to download the completed application.
(https://oracle.github.io/learning-library/developer-library/apex/remote-data-source/remotedatasource-app.sql)

**Comment by minqiaowang** [comment]
You can try this link instead:
https://raw.githubusercontent.com/oracle/learning-library/master/developer-library/apex/remote-data-source/remotedatesource-app.sql

**Comment by jegyed50** [comment]
Dear Minqiao Wang!

Thank you very much!
The link sent in the email works.
I was able to download the complete application.
The download link at the bottom of the
https://oracle.github.io/learning-library/developer-library/apex/remote-data-source/?page=README.md
 page still doesn't work.
Link on above page:
https://oracle.github.io/learning-library/developer-library/apex/remote-data-source/remotedatasource-app.sql
Link in your email:
https://raw.githubusercontent.com/oracle/learning-library/master/developer-library/apex/remote-data-source/remotedatesource-app.sql

Best regards,
Egyed József
Technical expert
Nuclear Power Plant of Paks, Hungary

Minqiao Wang <notifications@github.com> ezt írta (időpont: 2020. jún. 7.,
V, 12:06):

**Comment by minqiaowang** [comment]
There is an issue of the link. Maybe currently you can use the source page: https://github.com/oracle/learning-library/tree/master/developer-library/apex/remote-data-source

**Comment by tmcginn** [comment]
@minqiaowang - can you fix the link in the HOL? Thanks

**Comment by minqiaowang** [comment]
I have fixed the link and waiting for the pull request approve.

**Comment by tmcginn** [comment]
Done - closing this issue. Thanks @minqiaowang !
