### ISSUE TITLE
Oracle Multitenant Fundamentals - 3 Environment Setup - 

### ISSUE THREAD

**Issue by quintindhill** [oracle/learning-library#1433]
I have been working through the multitenant lab and found that the Image OCID doesn't work. It is hardcoded into the terraform file in the zip file that is used in resource manager. I went into platform images manually found the db 19.7 image and found that OCID and then substituted the ocid in the .tf file. I was able to get it to work, but I imagine this will be a major issue for the multitenant lab 

--Quintin Hill -- Cloud Engineer Santa Monica Hub

**Comment by tmcginn** [comment]
@kaymalcolm - is this issue fixed? If yes, can you close it? Thanks

**Comment by kaymalcolm** [comment]
It is in QA to confirm.  I will close.

On Jun 12, 2020, at 11:14 AM, Tom McGinn <notifications@github.com> wrote:


@kaymalcolm <https://urldefense.com/v3/__https://github.com/kaymalcolm__;!!GqivPVa7Brio!JaCkXVFkm3bZqLgZFjjP9K53ENbpe-9Ei3b3vYCvRecdHAZ8lIf5qGvdv2v88xr0nw$> - is this issue fixed? If yes, can you close it? Thanks
