### ISSUE TITLE
Please restore below link- a lot of my customers uses this workshop

### ISSUE THREAD

**Issue by haimb2019** [oracle/learning-library#1467]
https://oracle.github.io/learning-library/workshops/journey4-adwc/?page=LabGuide8.md

**Comment by snicholspa** [comment]
Hello, that workshop/lab has been deprecated.  It hadn't been updated in quite some time.  Please take a look at the following ADB/OML Workshop - https://oracle.github.io/learning-library/data-management-library/oracle-machine-learning/adb-oml/workshop/index.html?lab=introduction.

**Comment by haimb2019** [comment]
Steve

 

There was a link on how users can use free DV desktop to create canvases and visualizations. Where is that link.

 

Sample of what I created for my customer from that guidance , please restore that lab. I only see a basic scatter plot. Customer have seen the below demo and try it himself. 

 

Thanks so much in advance!

**Comment by haimb2019** [comment]
This missing section used be in the advanced user visualization part! It is creating additional canvases in DV desktop. Please help finding that.

 

Rest are ok- 

Thanks again!

From: Haimanti Basu 
Sent: Thursday, June 18, 2020 11:46 AM
To: oracle/learning-library <reply@reply.github.com>; oracle/learning-library <learning-library@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [oracle/learning-library] Please restore below link- a lot of my customers uses this workshop (#1467)

 

Steve

 

There was a link on how users can use free DV desktop to create canvases and visualizations. Where is that link.

 

Sample of what I created for my customer from that guidance , please restore that lab. I only see a basic scatter plot. Customer have seen the below demo and try it himself. 

 

Thanks so much in advance!

**Comment by chipbaber** [comment]
Haimanti,
As Steve mentioned the workshop material you are looking for has been depreciated. If you are looking for material on DV Desktop [ this link has excellent examples: ](https://docs.oracle.com/en/middleware/bi/analytics-desktop/bidvd/toc.htm)
