### ISSUE TITLE
ATP Instance 

### ISSUE THREAD

**Issue by khappy2help** [oracle/learning-library#1489]
Hi 
I have followed the instruction given on the below link.  
https://oracle.github.io/learning-library/oci-library/L100-LAB/ATP_Lab/ATP_HOL.html

The below step is getting fail with the mention error. 

Unzip the file:
unzip swingbench.zip

Error : [opc@atp1 ~]$ unzip swingbench.zip
Archive:  swingbench.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  swingbench.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of swingbench.zip or
        swingbench.zip.zip, and cannot find swingbench.zip.ZIP, period.

Kind regards
Ketan

**Comment by vrcrush** [comment]
having same problem here, I tried using wget to download the file but same issue.

**Comment by vrcrush** [comment]
hi @khappy2help , i was having the same problem but was able to download the file using w3m

First install w3m
apt­-get install w3m        (on APT based System)
 yum install w3m        (on YUM based System)

and this command to get the file
w3m http://www.dominicgiles.com/swingbench/swingbenchlatest.zip

then unzip like this
unzip swingbenchlatest.zip
