### ISSUE TITLE
Set up for multi-tenant labs no access to files for resource manager step

### ISSUE THREAD

**Issue by quintindhill** [oracle/learning-library#1491]
Step 1 of Lab3 has an updated .zip pre-authenticated request link that does not allow us to actually download the .zip folder. 
------
{"code":"BucketNotFound","message":"Either the bucket named 'labfiles' does not exist in the namespace 'c4u03' or you are not authorized to access it"}

**Comment by tmcginn** [comment]
This issue is fixed, please try again.
