### ISSUE TITLE
no access to object store fordb19c-compute-19.7.zip - Packaged terraform instance creation script

### ISSUE THREAD

**Issue by aksjadhav** [oracle/learning-library#1515]
Team, not able to download the terraform *.tf file from object store getting message no authorization.

Please check.

Thanks.

**Comment by troyanthony06** [comment]
What workshop are you running?
Is this the file that is failing (db19c-compute-v19-7.zip) or is it db19c-compute-19.7.zip as you state in the issue header?

**Comment by tmcginn** [comment]
Closing this issue - fixed in the workshop.
