### ISSUE TITLE
Oracle DB19c New Features for Developers Workshop - Terraform Apply Fails

### ISSUE THREAD

**Issue by flynnkc** [oracle/learning-library#1529]
When attempting to follow the Oracle DB19c New Features for Developers Workshop it fails on step 3 when I try to run the terraform apply job. The terraform plan job completes successfully. I'm using the db19c-compute-v19-7.zip file provided in the workshop.

The error it throws on Resource Manager is as follows:
Error: Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc request id: [...]

**Comment by tmcginn** [comment]
Hi, 
I believe this is now fixed. Can you try it again?
Thanks
