### ISSUE TITLE
Lab links from https://apexapps.oracle.com/pls/apex/f?p=44785:50:0:::50:P50_EVENT_ID,P50_COURSE_ID:5925,251 still don't work

### ISSUE THREAD

**Issue by ShivamPatel17** [oracle/learning-library#1532]
I saw there was a commit that said "fixed expired urls" but on the Learning Path Details for Autonomous Data Warehouse, the links for the labs bring up a 404 non found on github.

**Comment by tmcginn** [comment]
Hi,
Can you provide the links with the 404 errors and I'll track it down.
Thanks

**Comment by tmcginn** [comment]
Sorry, I followed the apex link and am following up with the developer.
Thanks
@greenrick

**Comment by tmcginn** [comment]
Closing this issue, please reopen if needed.

**Comment by tmcginn** [comment]
Closed
