### ISSUE TITLE
Creation of Apex application fails with ORA-20102 APEX$ATTRIBUTE_DEFAULTS does not exist ORA-06512

### ISSUE THREAD

**Issue by crskedu** [oracle/learning-library#1538]
ORA-20102: Application collection APEX$ATTRIBUTE_DEFAULTS does not exist ORA-06512: at "APEX_190200.WWV_FLOW_COLLECTION", line 2998 ORA-06512: at "APEX_190200.WWV_FLOW_COLLECTION", line 121 ORA-06512: at "APEX_190200.WWV_FLOW_COLLECTION", line 2898 ORA-06512: at "APEX_190200.WWV_FLOW_COLLECTION", line 2745 ORA-06512: at "APEX_190200.WWV_FLOW_APP_DEF_V3", line 1499 ORA-06512: at "APEX_190200.WWV_FLOW_APP_DEF_V3", line 1927 ORA-06512: at "APEX_190200.WWV_FLOW_APP_DEF_V3", line 1927 ORA-06512: at "APEX_190200.WWV_FLOW_CREATE_APP_V3", line 4926 ORA-06512: at line 38

![image](https://user-images.githubusercontent.com/57941589/86528455-7e98cf80-bec5-11ea-9e92-caef659cc76e.png)

**Comment by tmcginn** [comment]
Hi,
Which workshop and lab were you working on?
Thanks

**Comment by tmcginn** [comment]
Closing this issue, please reopen if needed.
