### ISSUE TITLE
Terraform and Oracle Cloud Infrastructure HOL missing pictures

### ISSUE THREAD

**Issue by sa2sa2** [oracle/learning-library#1570]
Terraform and Oracle Cloud Infrastructure HOL is missing some pictures :

https://oracle.github.io/learning-library/oci-library/DevOps/Terraform-and-OKE-LAB/tf_oke_hol.html

the links of the missing pictures :

https://raw.githubusercontent.com/oracle/learning-library/master/oci-library/Foundational/Network_Compute_and_Block_Service/media/image1.png

https://raw.githubusercontent.com/oracle/learning-library/master/oci-library/Foundational/Identity_Access_Management/img/image001.png

**Comment by tmcginn** [comment]
Updated in LiveLabs: http://bit.ly/golivelabs
