### ISSUE TITLE
Container Registry Practice contains bunch of low resolution images

### ISSUE THREAD

**Issue by sa2sa2** [oracle/learning-library#1572]
Container Registry Practice contains bunch of low resolution images :

https://oracle.github.io/learning-library/oci-library/DevOps/Container_Registry/Container_Registry_HOL.html

which makes the HOL hard to follow because of these low resolution images, it would be beneficial if the HOL pictures are clear enough so that it can be followed easily.

**Comment by tmcginn** [comment]
This is one that we did port to LiveLabs: http://bit.ly/golivelabs
