### ISSUE TITLE
Application Continuity Workshop for Oracle DB19c New Features for Developers is still coming soon since APR 2020

### ISSUE THREAD

**Issue by sa2sa2** [oracle/learning-library#1574]
Application Continuity Workshop for Oracle DB19c New Features for Developers is still coming soon since April 2020 :

https://oracle.github.io/learning-library/developer-library/oracle-db-features-for-developers/freetier/index.html?lab=lab-6-application-continuity---coming

**Comment by tmcginn** [comment]
Agreed.
I took that lab out of the workshop for now.
Thanks
