### ISSUE TITLE
Lab 3 is missing from Oracle Autonomous Database Dedicated Workshop

### ISSUE THREAD

**Issue by sa2sa2** [oracle/learning-library#1577]
Lab 3 is missing from Oracle Autonomous Database Dedicated Workshop :

https://oracle.github.io/learning-library/data-management-library/autonomous-database/dedicated/workshop/

or this is just a wrong numbering order ?!

**Comment by tmcginn** [comment]
I fixed the numbering order, thanks for pointing that out.
Tom
