### ISSUE TITLE
Level 50 - Foundations – Compute Services - page 10 spelling mistake

### ISSUE THREAD

**Issue by sa2sa2** [oracle/learning-library#1580]
Level 50 - Foundations – Compute Services - page 10 spelling mistake :

https://www.oracle.com/a/ocom/docs/cloud-training-compute-services.pdf

New shape must have the sOme hardware architecture.

should be corrected to :

New shape must have the sAme hardware architecture.

**Comment by tmcginn** [comment]
Hi sa2sa2, not sure where you found the link to the PDF?
It isn't referenced from GitHub...

**Comment by tmcginn** [comment]
Closing this issue, please reopen if needed.
