### ISSUE TITLE
unable to access object for lab

### ISSUE THREAD

**Issue by seventhletterman** [oracle/learning-library#1586]
link http://bit.ly/2yOzzVE provided on Autonomous Data Warehouse lab (https://oracle.github.io/learning-library/oci-library/L100-LAB/Autonomous_Data_Warehouse/ADW_HOL.html) is returning error message "BucketNotFound"
![ADW error](https://user-images.githubusercontent.com/68269606/87406624-3c584800-c5c1-11ea-98c1-75a5ffe5bbd1.JPG)

**Comment by tmcginn** [comment]
@jdavies - can you take a look?

**Comment by jdavies** [comment]
I've been meaning to update that lab (all f the Level-100 labs actually). Use this link to get the channels.txt file: https://docs.oracle.com/en/cloud/paas/autonomous-data-warehouse-cloud/adwud/load-using-dbms_cloud-copy_data.html#GUID-F0A7FB84-24C2-4D89-ABAD-BC455FFE1B28

**Comment by seventhletterman** [comment]
Sorted, thanks.
