### ISSUE TITLE
git push fatal error

### ISSUE THREAD

**Issue by hjavaherian** [oracle/learning-library#1604]
When running git push to the master I run into this error:
$ git push origin master
Enumerating objects: 87963, done.
Counting objects: 100% (87963/87963), done.
Delta compression using up to 8 threads
Compressing objects: 100% (47644/47644), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
Writing objects: 100% (87963/87963), 3.56 GiB | 2.81 MiB/s, done.
Total 87963 (delta 34579), reused 87933 (delta 34565), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by tmcginn** [comment]
Closing this issue due to it's age. Please reopen it if this is still an issue.
