### ISSUE TITLE
What's the purpose of the public compute instance in the NAT gateway lab?

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle/learning-library#1851]
The readme for the NAT gateway lab ...

https://github.com/oracle/learning-library/blob/master/oci-library/oci-hol/nat-gateway/nat-gateway/nat-gateway.md

... includes instructions to create (1) a compute instance that's attached to a public subnet and (2) another compute instance attached to a private subnet.

What's the purpose of first compute instance, i.e., the one attached to the public subnet in the context of the NAT gateway?

**Comment by flavio-santino** [comment]
The reason is that this instance will be used as a jump server, similar to a bastion host. So, you can access the private instance.

**Comment by kumar-dhanagopal** [comment]
Thanks for clarifying that, @flavio-santino .  

@kaymalcolm - I suggest updating the instructions in the lab to make the purpose of the public instance clear. Let me know if you'd like me to open a new issue for that. Thank you!
