### ISSUE TITLE
Inconsistent images in Lab1

### ISSUE THREAD

**Issue by aalmiray** [oracle/learning-library#1893]
As seen at https://oracle.github.io/learning-library/developer-library/micronaut-oci-atp/workshops/freetier/?lab=lab-1-generate-ssh-keys#Introduction

* Option1: Oracle Cloud Shell
** The image describing the usage of ssh-keygen mentionds "cloudshellkey" as output.
 The next image however blurrs the generated files which are clearly "cloudshellkey" and "cloudshellkey.pub"
** The username@host (kay_malcol) is blurred in some screnshots but not all.
* Option 2: MacOS
** username "theking" is visible in some screnshots and blurred in others.
** host "Tylers-MacBook-Pro-2" is visible in most screnshots, partially blurred in others.
* Option 3: Windows 10
** username "dkingsle" is visible in some screenshots.
** host "DKINGSLE_US" is visible in some screenshots.
* Option 4a: Prior Windows Versions - Git for Windows
** username "dkingsle" is visible in some screenshots.
** host "DKINGSLE_US" is visible in some screenshots.
* Option 4b: Windows Versions - PuTTY
** username "dkingsle" is visible in some screenshots.
* Option 5: SSH Keys for Linux
** host "mgmnt-01" is visible in some screenshots but blurred in others.
** why blurr "id_rsa" in the screenshot while explicitly mentioning the output file by name in this step (and others)?

**Comment by tmcginn** [comment]
Thanks @aalmiray , I'll update the lab

**Comment by tmcginn** [comment]
Completed: https://github.com/oracle/learning-library/pull/1964
