### ISSUE TITLE
Extending your APEX App with Autonomous Database Features - Lab 2: Add Spatial to APEX

### ISSUE THREAD

**Issue by PriscilaIruela** [oracle/learning-library#1939]
Lab2 doesn't work (ORDS 500 Internal Error) at STEP 1: Import the APEX application when we import the file f105.sql. This file has a command that doesn't allow installing supporting objects by APEX.
I have been working with Patrick Wolf (APEX PM) to fix the problem.

Patrick have been able to find out what causes the ORDS 500 Internal Error
It’s the following statement which is executed as part of the Supporting Objects when you install the application
update drone_permit_req set permit = null;
looks like this causes an ORA-600 in the database
I don’t think it’s actually necessary during installation, because the tables have just been created and are empty

Patrick has created a version of your app where that script is commented out -> condition set to Never

Can you please change the f105.sql that the lab has to download in Step 1 part 1 - 'First, click this link to download the application that we will install.'
By the attached file, please?
The new file is stored here - https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/36FU1d16VFi7D4iOOsIcQ1fNKjBqUTSfUz8nb6c14OlqF732BmL65CNFUqRj-qJZ/n/odca/b/PublicDocs/o/f105_new.sql

Thanks in advance! We are running this lab next week (8th of October) with customers and the new file has to be replace asap.
@tmcginn , can you point me whom can help us to replace the file asap?

Thanks in advance everyone.

Best regards, 
Priscila

**Comment by tmcginn** [comment]
Done. @PriscilaIruela - you might want to see if you can get https://github.com/oracle/cloudtestdrive/pull/80 pushed through on your end.
