### ISSUE TITLE
"fn start" fails due to docker version too old

### ISSUE THREAD

**Issue by ranaanimesh** [oracle/learning-library#207]
Tried STEP 1 in LabGuide500.md
Run into Docker too old error.

[oracle@OL74-ClientImage ~]$ fn start
time="2018-04-10T20:56:03Z" level=info msg="Setting log level to" level=info
time="2018-04-10T20:56:03Z" level=info msg="datastore dialed" datastore=sqlite3 max_idle_connections=256
time="2018-04-10T20:56:03Z" level=info msg="agent starting cfg=&{MinDockerVersion:17.10.0-ce FreezeIdle:50ms EjectIdle:1s HotPoll:200ms HotLauncherTimeout:1h0m0s AsyncChewPoll:1m0s CallEndTimeout:10m0s MaxCallEndStacking:8192 MaxResponseSize:0 MaxLogSize:1048576 MaxTotalCPU:0 MaxTotalMemory:0 MaxFsSize:0 PreForkPoolSize:0 PreForkImage:busybox PreForkCmd:tail -f /dev/null PreForkUseOnce:0 PreForkNetworks:}"
time="2018-04-10T20:56:03Z" level=info msg="no docker auths from config files found (this is fine)" error="open /root/.dockercfg: no such file or directory"
time="2018-04-10T20:56:03Z" level=fatal msg="docker version error" error="docker version is too old. Required: 17.10.0-ce Found: 17.06.2-ol"
2018/04/10 13:56:03 error: processed finished with error exit status 1

**Comment by derekoneil** [comment]
We are preparing to release a new client VM version with a new version of Docker installed (hopefully tomorrow). I'll also update with instructions to add the required yum repo to update your existing client.
