### ISSUE TITLE
Broken Link in Workshop README for JCS Pipeline Workshop

### ISSUE THREAD

**Issue by ranched** [oracle/learning-library#235]
The link to the workshop "JCS Pipeline using Oracle Stack Manager" is broken in "learning-library/workshops/README.md"
[https://github.com/oracle/learning-library/tree/master/workshops#workshops-and-hands-on-labs](url)

Broken:
`| JCS Pipeline using Oracle Stack Manager | [jcs-devops](https://oracle.github.io/cloud-native-devops-workshop/jcs-devops/) | Hands-on-labs showing a Software Development Lifecycle using the Oracle Developer Cloud Services, Java Cloud Service and Oracle Stack Manager.|`

Looks like it should be:
`| JCS Pipeline using Oracle Stack Manager | [jcs-devops](https://oracle.github.io/learning-library/workshops/jcs-devops/) | Hands-on-labs showing a Software Development Lifecycle using the Oracle Developer Cloud Services, Java Cloud Service and Oracle Stack Manager.|`

**Comment by derekoneil** [comment]
fixed, thanks!
