### ISSUE TITLE
Private DNS Live Lab 2: Configuring Private DNS - Incorrect output (#2354)

### ISSUE THREAD

**Issue by bhaworth** [oracle/learning-library#2369]
The correction made in #2367 has only fixed the FQDN in the output; the IP is still incorrect. It should be `10.10.0.123`

**Comment by kaymalcolm** [comment]
Hi, the correct location for issues related to LiveLabs is https://community.oracle.com/community/groundbreakers/livelabs.  This issues list is not actively monitored.
