### ISSUE TITLE
Oracle Data Visualization Desktop doesn't have the connector for Big Data

### ISSUE THREAD

**Issue by MeghaGajbhiye** [oracle/learning-library#238]
Please see the attachment enclosed.
<img width="1437" alt="screen shot 2018-06-27 at 4 17 26 pm" src="https://user-images.githubusercontent.com/14322255/42000222-a1953c4e-7a25-11e8-80c5-a25bf2e870a2.png">

**Comment by MeghaGajbhiye** [comment]
I am using MAC OS

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
