### ISSUE TITLE
DBCS monitor deprecated and replaced by SQL Developer WEB

### ISSUE THREAD

**Issue by aorcl** [oracle/learning-library#239]
Hello,
In the workshop "dbcs / CloudWorkshop_DBCS_100.md, the section "STEP 11: Access Database Monitor" isn't relevant anymore - the DB Monitor was replaced by SQL Developer WEB and this part of the workshop isn't usable.

https://github.com/oracle/learning-library/blob/master/workshops/dbcs/CloudWorkshop_DBCS_100.md

Regards

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
