### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound] 

### ISSUE THREAD

**Issue by MrCull** [oracle/learning-library#2410]
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:

Status code [404:NotFound] - Link: http://bit.ly/golivelabs/

This is the link under this image:
![image](https://user-images.githubusercontent.com/16634034/102690079-d5d3f780-41fa-11eb-9c06-427ecb68485c.png)

This links to:
![image](https://user-images.githubusercontent.com/16634034/102690112-03b93c00-41fb-11eb-9cd6-e9c9f972d503.png)

**Extra**

This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts here, or log an “Issue” in the repo.

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2foracle%2flearning-library

**Comment by tmcginn** [comment]
Thanks very much! It is a subtle error - the trailing slash / on the end of URL. At least, I think that's issue. When my PR is approved, I'll recheck the repo.

**Comment by MrCull** [comment]
This is now resolved by #2414

In future it might make more sense to use the proper link: "https://apexapps.oracle.com/pls/apex/f?p=133:1" ??
