### ISSUE TITLE
Cannot export encrypted schema alphaclone , ora-28374

### ISSUE THREAD

**Issue by anshoee** [oracle/learning-library#244]
Lab 200 : Step 10 -
   Export doesn't run at all - it simply keeps popping error ora-28374 : Typed key not found in wallet . I didn't type any key anywhere before running the export. When I try the same expdp command with the encryption_password clause, it still pops the same error. Any clues ? 
   The Lab doc. screenshot doesn't show anything about how to handle encryption at this step 10.

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
