### ISSUE TITLE
face issue when doing copy_data in adw lab

### ISSUE THREAD

**Issue by leeadh** [oracle/learning-library#245]
Hi, 

define url = 'https://swiftobjectstorage.us-ashburn-1.oraclecloud.com/v1/xxx/Sales_Data/CHANNELS.csv'

BEGIN
 dbms_cloud.copy_data(
    table_name =>'CHANNELS',
    credential_name =>'SALES_DATA_AUTH',
    file_uri_list =>'&url',
    format => json_object('delimiter' value ',','skipheaders' value 1,
                        'ignoremissingcolumns' value 'true',
                        'removequotes' value 'true',
                        'dateformat' value 'DD-MON-YYYY',
                        'blankasnull' value 'true')
 );
END;

I got this error

END;
Error report -
ORA-29913: error in executing ODCIEXTTABLEFETCH callout
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 801
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 782
ORA-30653: reject limit reached
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 757
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 819
ORA-06512: at line 2
29913. 00000 -  "error in executing %s callout"
*Cause:    The execution of the specified callout caused an error.
*Action:   Examine the error messages take appropriate action.

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
