### ISSUE TITLE
[Image needs update] Compute-Console-Connection

### ISSUE THREAD

**Issue by davidkhala** [oracle/learning-library#2477]
The tutorial in 
https://github.com/oracle/learning-library/blob/master/oci-library/L200-LAB/Compute-Console-Connection/HOL-Console-Connection.md

mismatch with current OCI console UI

![image](https://user-images.githubusercontent.com/7227589/105015292-5eed8100-5a7c-11eb-902a-580aef496252.png)
I think it is an indicator that this tutorial is somehow out-date. Please review as a whole. Thanks.

**Comment by tmcginn** [comment]
@oegentil - can you pull this content down?

**Comment by oegentil** [comment]
PR submitted with updates
