### ISSUE TITLE
oracle

### ISSUE THREAD

**Issue by anbukarasan** [oracle/learning-library#251]

**Comment by derekoneil** [comment]
Hello, it looks like your message got lost; all I see is a blank issue. how can I help?

**Comment by anbukarasan** [comment]
i clicked on wrong button / fat finger. kindly ignore.
Thanks.Anbu a.k.a Murali 

    On Monday, September 10, 2018, 4:18:56 PM PDT, derekoneil <notifications@github.com> wrote:  
 
 
Hello, it looks like your message got lost; all I see is a blank issue. how can I help?
