### ISSUE TITLE
Start Fn Server issue

### ISSUE THREAD

**Issue by rtolefree1** [oracle/learning-library#254]
Having issue starting the Fn server for Lab 500. I'm getting the following error:
time="2018-09-25T14:53:58Z" level=info msg="mysql does not support sqlite3"
:false DisableDebugUserLogs:false IOFSPath: IOFSOpts:}"
time="2018-09-25T14:53:58Z" level=info msg="no docker auths from config files found (this is fine)" error="open /root/.dockercfg: no such file or directory"
time="2018-09-25T14:53:58Z" level=fatal msg="docker version error" error="docker version is too old. Required: 17.10.0-ce Found: 17.06.2-ol"

Please directions to update to the latest docker version 17.10 or higher. This is on the Oracle provided Virtual box. If there is another fix to this issue other than upgrade to newer version please provide

**Comment by derekoneil** [comment]
Hello,

It is possible that you are using an older version of our VirtualBox image. You can download the latest image from the link in Lab 200 ("Download VirtualBox Image"). 

The direct link is currently: [here](https://objectstorage.us-ashburn-1.oraclecloud.com/p/IaJSPgOrsUTbMhn3KPaaO0PJGZ2vuF-FCt2ELEkW2ck/n/gse00014514/b/PublicBucket/o/OL74_ClientImagev1.01.ova), however this does change whenever we release an updated version. 

If you do not want to redo any of the lab steps on a different image, you can alternatively update Docker to a newer version on your current image -- that is the only fix needed to get Fn running.


-Derek

**Comment by rtolefree1** [comment]
Hi Derek,
Thanks for the update! I will download the newer version later this week and try again.

Ricky

**Comment by rtolefree1** [comment]
First, I verified that I am using the latest version of the VirtualBox image: OL74_ClientImagev1.01.ova
Next,
I tried to do a update to environment and I receive the following error:
[oracle@OL74-ClientImage ~]$ sudo apt-get update
sudo: apt-get: command not found

Then, I change to the root user and ran the same command and got the same error. Then lastly I did a find on 'apt-get':
[root@OL74-ClientImage oracle]# sudo find / -name 'apt-get'
[root@OL74-ClientImage oracle]#

And the command was not found. I do not think I have the ability to update docker on my image. Can you please assist?

**Comment by rtolefree1** [comment]
Good Evening Derek,
First, I verified that I am using the latest version of the VirtualBox image: OL74_ClientImagev1.01.ova
Next,
I tried to do a update to environment and I receive the following error:
[oracle@OL74-ClientImage ~]$ sudo apt-get update
sudo: apt-get: command not found

Then, I change to the root user and ran the same command and got the same error. Then lastly I did a find on 'apt-get':
[root@OL74-ClientImage oracle]# sudo find / -name 'apt-get'
[root@OL74-ClientImage oracle]#

And the command was not found. I do not think I have the ability to update docker on my image. Can you please assist?

**Comment by aorcl** [comment]
Hello, @rtolefree1 I'm not Derek but i have an answer :)
You use apt-get package manager on Ubuntu only - on Oracle Linux, Centos or RHEL the package manager is "yum". To update OL you do "sudo yum update".
Regards :)

**Comment by rtolefree1** [comment]
ok, thanks!

**Comment by rtolefree1** [comment]
Cool, installation completed and able to start my fn server...which was the initial issue. Thanks

Thanks!

**Comment by rtolefree1** [comment]
I clone the application code and now trying to deploy to FN server but getting the following:
ERROR: Put http://localhost:8080/v1/apps/imgconvert/routes/resize128: dial tcp [::1]:8080: getsockopt: connection refused

Please let me know your thoughts

**Comment by rtolefree1** [comment]
Nevermind, please ignore error...should have did more research...thanks
