### ISSUE TITLE
Dead links in a lab

### ISSUE THREAD

**Issue by LotToLearn** [oracle/learning-library#2558]
Hi,

Lab 2 and 3 are dead links and should be taken down

https://datateamreston.github.io/DatabaseConsolidation-Dev/workshop/index.html?lab=introduction-consolidation-databases#Acknowledgements

**Comment by tmcginn** [comment]
This content is not on this repo, you'll have to leave this comment on the datatemreston repo.

**Comment by LotToLearn** [comment]
Okay, thanks. The link went to this one so I'll also let them know about that
