### ISSUE TITLE
CND Lab 500: Fn deploy local error

### ISSUE THREAD

**Issue by dpandit-bias** [oracle/learning-library#271]
I receive following error when trying deploy the image resize function to a local Fn server:

$ fn deploy --app imgconvert --local
Deploying resize128 to app: imgconvert at path: /resize128
Bumped to version 0.0.13
Building image resize128:0.0.13 
Updating route /resize128 using image resize128:0.0.13...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x955ab4]

goroutine 1 [running]:
main.(*routesCmd).putRoute(0xc420513620, 0xc42006ab00, 0x7ffd2590138a, 0xa, 0xc420515870, 0xa, 0xc42011aee0, 0x0, 0xaa3243)
	/home/circleci/go/src/github.com/fnproject/cli/routes.go:441 +0x364
main.(*deploycmd).updateRoute(0xc4203312c0, 0xc42006ab00, 0x7ffd2590138a, 0xa, 0xc420406a20, 0xc420406a20, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:268 +0x261
main.(*deploycmd).deployFunc(0xc4203312c0, 0xc42006ab00, 0x7ffd2590138a, 0xa, 0xc42000c184, 0x19, 0xc420354510, 0x23, 0xc420406a20, 0xc4205137c0, ...)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:246 +0x35b
main.(*deploycmd).deploySingle(0xc4203312c0, 0xc42006ab00, 0x7ffd2590138a, 0xa, 0x0, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:152 +0x171
main.(*deploycmd).deploy(0xc4203312c0, 0xc42006ab00, 0x1, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:122 +0x10a
main.(*deploycmd).(main.deploy)-fm(0xc42006ab00, 0x0, 0xc420515720)
	/home/circleci/go/src/github.com/fnproject/cli/deploy.go:27 +0x34
github.com/fnproject/cli/vendor/github.com/urfave/cli.HandleAction(0x9d5660, 0xc420515160, 0xc42006ab00, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:490 +0xd4
main.prepareCmdArgsValidation.func1(0xc42006ab00, 0x100, 0xc42006ab00)
	/home/circleci/go/src/github.com/fnproject/cli/main.go:125 +0x276
github.com/fnproject/cli/vendor/github.com/urfave/cli.HandleAction(0x9d5660, 0xc4203fcb40, 0xc42006ab00, 0xc4202f1200, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:490 +0xd4
github.com/fnproject/cli/vendor/github.com/urfave/cli.Command.Run(0xa9e78b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xac3aef, 0x54, 0x0, ...)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/command.go:210 +0xb6e
github.com/fnproject/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4200dfa00, 0xc4200100f0, 0x5, 0x5, 0x0, 0x0)
	/home/circleci/go/src/github.com/fnproject/cli/vendor/github.com/urfave/cli/app.go:255 +0x76f
main.main()
	/home/circleci/go/src/github.com/fnproject/cli/main.go:133 +0x57

**Comment by tmcginn** [comment]
No new updates, please reopen if required.
