### ISSUE TITLE
Need an update to a step in the Cloud native workshop

### ISSUE THREAD

**Issue by rishgh** [oracle/learning-library#2832]
Need an update to the following Oracle Livelabs github page - https://oracle.github.io/learning-library/oci-library/oci-hol/cloud-native/workshops/freetier/i

The lab "Setup Cloud Environment" under "Introduction to Cloud native" has a "step 3: Create OKE Kubernetes Cluster".  Within this flow, step 4 has the following text and attached screenshot that needs an update .

**Current Text:**
Keep the name to cluster1 and the other default values, click Next to review the cluster settings
<In red>Optionally choose visibility type to Public if you want public access to your nodes and number of nodes to 2 or 1 if you want reduced number of nodes <In red>

**Proposed text change**

Keep the name to cluster1 and the other default values, click Next to review the cluster settings
<In Red>Optionally choose visibility type to Private Endpoint to host your Kubernetes endpoint in a private subnet.  Also choose visibility type to Public Workers if you want public access to your nodes. You can also change the number of nodes to 2 or 1 if you want to reduce the number of nodes.<In Red>

<img width="931" alt="newscreenshot" src="https://user-images.githubusercontent.com/36372417/112915398-cef33580-90c3-11eb-94e0-624b3fd551a6.png">
<img width="689" alt="old screenshot" src="https://user-images.githubusercontent.com/36372417/112915399-cf8bcc00-90c3-11eb-9f15-b277965a204c.png">

**Comment by oegentil** [comment]
Update refresh for MuShop #2868
