### ISSUE TITLE
Signing to Advanced Analytics or Oracle Analytics Cloud?

### ISSUE THREAD

**Issue by ykliu2016** [oracle/learning-library#313]
https://oracle.github.io/learning-library/workshops/adwc4dev/?version=Self-Guided&page=L400.md

In this lab 400, the step one says Sign in to Oracle Advanced Analytics and import the Sales.dva project. I suppose this is a typo but can be very confusing to those who don't have too much knowledge about Oracle analytics solutions. Shouldn't this be Oracle Analytics Cloud instead of Advanced Analytics?

**Comment by balatino** [comment]
Yes, I suppose the same..

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
