### ISSUE TITLE
Not seeing all the tables for the Analytics Lab : workshops/adwc4dev/L400.md

### ISSUE THREAD

**Issue by vijaykumaryenne** [oracle/learning-library#314]
In lab 4, it mentions to load all the below data sets:
AI_EXPLAIN_OUTPUT_CREDIT_SCORE_BIN
AI_EXPLAIN_OUTPUT_MAX_CC_SPENT_AMOUNT
CREDIT_SCORING_100K_V
CREDIT_SCORE_NEW_PREDICTIONS
N1_LIFT_TABLE

However, in the Shema that has been shared or created in the previous lab only talks about :CREDIT_SCORING_100K_V

Don't see any other schemas shared. Am I missing anything?

**Comment by dgcameron** [comment]
These tables are created by machine learning processes in steps 9 - 11 of lab 300.  If you skipped those steps the tables will not exist.  In lab 400 we create visualizations on the results of the machine learning analysis.  Go back and make sure you run all the steps in lab 300.
