### ISSUE TITLE
Lab 100 STEP 5: initial wercker.yml file needs jdk version in box definition

### ISSUE THREAD

**Issue by fharris** [oracle/learning-library#318]
#Use OpenJDK base docker image from dockerhub and open the application port on the docker container
box:
  id: openjdk:8
  ports:
    - $PORT

#Build our application using Maven, just as we always have
build:
  steps:
    - install-packages:
        packages: maven
    - script:
        name: maven build
code: mvn clean assembly:assembly

**Comment by derekoneil** [comment]
Hi fharris,
Looks like the jdk version is there in the code box.. are you referring to the screenshot below it?

**Comment by fharris** [comment]
Thanks Derek. You're right. The jdk version is in the code itself, but the screenshots and the snippet to copy in the tutorial steps aren't updated.
