### ISSUE TITLE
Errors in Lab 500: Test imgconvert Function

### ISSUE THREAD

**Issue by Denthor2985** [oracle/learning-library#327]
Step 4

Fn version: v0.3.632

Errors envountered:
time="2018-12-10T07:18:11Z" level=info msg="hot function terminated" app_id=01CYBF0K0VNG8G00GZJ0000001 cpus= error="container exit code 1" fn_id=01CYBF0K1WNG8G00GZJ0000002 id=01CYBFNZKGNG8G00GZJ0000002 idle_timeout=30 image="resize128:0.0.5" memory=128
time="2018-12-10T07:18:11Z" level=error msg="api error" action="server.handleHTTPTriggerCall)-fm" appName=imgconvert code=502 error="container failed to initialize, please ensure you are using the latest fdk / format and check the logs" triggerSource=/resize128

No workaround

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
