### ISSUE TITLE
LAB 200 : Getting Error When Creating KubeConfig

### ISSUE THREAD

**Issue by sjoshi-oracle** [oracle/learning-library#340]
Hi, 

I have followed the instructions to the letter but I am getting the following error when trying to Create the KubeConfig

[opc@instance-20190109-1525 ~]$ oci ce cluster create-kubeconfig --cluster-id ocid1.cluster.oc1.eu-frankfurt-1.aaaaaaaaafsdamlcgjrtsm3gmezdqyzumq2wezlege4geojzgc2wgzdggfsw --file $HOME/.kube/config --region eu-frankfurt-1
ServiceError:
{
    "code": null,
    "message": "code: NotAuthorizedOrNotFound\nmessage: Authorization failed or requested resource not found.\n",
    "opc-request-id": "32B4C4A9A4E14D1CB213733DF467ACC5/6B14F36031E04CDA968E11F740513018/26C86ACA91624131BFA61F9890544A52",
    "status": 404
}

I have done my public key and OCI Setup config 10 time and still the same error

**Comment by derekoneil** [comment]
For trial accounts, the account owner is already in the OCI administrators group, so no further configuration is required.
