### ISSUE TITLE
Step 12: The modal will then give you a preview of what the data will look ... Error while parsing

### ISSUE THREAD

**Issue by neit-group-admin** [oracle/learning-library#3419]
[NEIT_TAS_deal_detail_stofira_v001_F_2021-07-20-15-42-12_super_short.txt](https://github.com/oracle/learning-library/files/6867612/NEIT_TAS_deal_detail_stofira_v001_F_2021-07-20-15-42-12_super_short.txt)

Hello everyone.
Not able to go throgh the step 12: Upload Data Into New Table

We get the following message:
Error while parsing the file NEIT~TAS~deal_detail_stofira~v001~F~2021-07-20-15-42_super_short.txt_

**It happens when "|" is used as the separator.**

The file is attached.
Are we doing something wrong? Is something wrong with the file? Any other way?

Thanks a lot and regards,
Vaclav

**Comment by Mmm-Biscuits** [comment]
Please use the CSV that is provided for you in the lab.
