### ISSUE TITLE
Issue with pushing the docker image to docker registry

### ISSUE THREAD

**Issue by sjoshi-oracle** [oracle/learning-library#343]
In the LabGuide 100 -> Step 6 the Docker registry is fixed to iad.ocir.io however the first part should be the region the user has got the trial account or their account set up. As in Lab 200 when pushing it will fail if users are not having Asbhurn region as their DC.  

where <region-code> corresponds to the code for the Oracle Cloud Infrastructure Registry region you're using, as follows:
enter fra as the region code for Frankfurt
enter iad as the region code for Ashburn
enter lhr as the region code for London
enter phx as the region code for Phoenix

**Comment by derekoneil** [comment]
Fixed with 437abe3
