### ISSUE TITLE
Product's twitter feed is not being displayed

### ISSUE THREAD

**Issue by sivachunduru** [oracle/learning-library#353]
In Step 15, Product's twitter feed is not rendering for Crayola New Marker. Instead, it is showing File Upload option with a label of 'Upload an Image'.

**Comment by derekoneil** [comment]
Hi Siva -- Did the validation of the twitter-feed service in Step 13 (using curl) work successfully? If so, did your Kubernetes service get named "twitter-feed"? If the name is changed, the product catalog will not be able to locate the service.

**Comment by sivachunduru** [comment]
Hi,

In step-13, I get the below result from curl command.

{"tweets" : [{"created_at":"Tue Aug 16 19:09:09 +0000 2016","id":765626469619859500,"id_str":"765626469619859456","text":"The VICTORIOUS SESSIONS at Little Johnny Russells PLEASE SHARE or come on down https://t.co/9DGGpEX0js","source":"<a href=\"http://www.facebook.com/twitter\" rel=\"nofollow\">Facebook</a>","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":23947154,"id_str":"23947154","name":"Nick Courtney","screen_name":"NickCourtney","location":"Portsmouth, UK","url":"http://www.vinylrecords.co.uk","description":"Independent Music Promoter booking agent (Victorious Festival) http://www.book.events and Sweet Memories Vinyl Records https://www.facebook.com/nickcourtney","protected":false,"verified":false,"followers_count":1399,"friends_count":592,"listed_count":21,"favourites_count":599,"statuses_count":17772,"created_at":"Thu Mar 12 13:35:46 +0000 2009"

My Kubernetes service name is "twitter-feed" only.

Still, it does not render as expected. Else, the screenshot in the tutorial could be wrong (the section it shows "145 Tweets Total").

Thanks,
Siva
