### ISSUE TITLE
Deploy the function locally only works with --create-app option

### ISSUE THREAD

**Issue by lsarecz** [oracle/learning-library#355]
In STEP 3 (Deploy the Function Locally) `fn deploy --app imgconvert --local` results an error:
`Fn: app imgconvert not found`
I could only deploy it with this command:   
`fn deploy --app imgconvert --create-app --local`

**Comment by lsarecz** [comment]
The same applies for STEP 6 when deploying to remote fn server.

**Comment by derekoneil** [comment]
Thanks!
