### ISSUE TITLE
Lab 300 - Machine Learning

### ISSUE THREAD

**Issue by vikramfin** [oracle/learning-library#359]
While copying data

begin
 dbms_cloud.copy_data(
    table_name =>'credit_scoring_100k',
    credential_name =>'adwc_token',
    file_uri_list => 'https://swiftobjectstorage.eu-frankfurt-1.oraclecloud.com/v1/ocdc/adwc/credit_scoring_100k.csv',
    format => json_object('ignoremissingcolumns' value 'true', 'removequotes' value 'true', 'dateformat' value 'YYYY-MM-DD HH24:MI:SS', 'blankasnull' value 'true', 'delimiter' value ',')
 );
end;

the below error is reported
ORA-20003: Reject limit reached, query table "ADMIN"."COPY$23_LOG" for error details
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 535
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 1013
ORA-06512: at "C##CLOUD$SERVICE.DBMS_CLOUD", line 1036
ORA-06512: at line 2

**Comment by brenorc** [comment]
If you take a look at the table "ADMIN"."COPY$23_LOG" you will find the reason for your error. I had the same issue, read the log and found out the database was trying to import the header row from the .csv file as data, what caused an error. You can change the input command to skip the first row or manually delete the header row from the .csv file and it will probably work.

**Comment by m1nka** [comment]
There are two errors in the tutorial. The first one as mentioned, and also the object storage URL is wrong in the tutorial.

**Comment by jdruizperea** [comment]
you can add 'skipheaders' value '1' in the format section of the copy_data statement to avoid this error. So format would be like this:
format => json_object('ignoremissingcolumns' value 'true', 'removequotes' value 'true', 'dateformat' value 'YYYY-MM-DD HH24:MI:SS', 'blankasnull' value 'true', 'delimiter' value ',', 'skipheaders' value '1')

Still the notebook should be updated to correct this

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
