### ISSUE TITLE
Missing images in terraform lab

### ISSUE THREAD

**Issue by aorcl** [oracle/learning-library#363]
Hello,
Some images referenced by https://oracle.github.io/learning-library/oci-library/DevOps/Terraform/Terraform_HOL.html aren't there anymore.

Regards

**Comment by albertyckwok** [comment]
I found most of the missing images and have updated Terraform_HOL.html on my local repos. Please let me know how/if I can create a branch, and submit PR (Pull Request).
Regards
Albert

**Comment by albertyckwok** [comment]
Sorry, it doesn't look like I have permission to push update to the repository. The following is what I did and get:
```
akwok@DESKTOP-7JNMR77 MSYS ~/sources/learning-library (master)
$ git checkout -b branchToFixIssue363
Switched to a new branch 'branchToFixIssue363'

akwok@DESKTOP-7JNMR77 MSYS ~/sources/learning-library (branchToFixIssue363)
$ git add oci-library/DevOps/Terraform/Terraform_HOL.md
warning: LF will be replaced by CRLF in oci-library/DevOps/Terraform/Terraform_HOL.md.
The file will have its original line endings in your working directory

akwok@DESKTOP-7JNMR77 MSYS ~/sources/learning-library (branchToFixIssue363)
$ git commit -m "Fix missing image links for Terraform lab"
[branchToFixIssue363 2e6fbdeaa] Fix missing image links for Terraform lab
 1 file changed, 14 insertions(+), 17 deletions(-)

akwok@DESKTOP-7JNMR77 MSYS ~/sources/learning-library (branchToFixIssue363)
$ git push origin branchToFixIssue363
ERROR: Permission to oracle/learning-library.git denied to albertyckwok.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tmcginn** [comment]
@albertyckwok - did you get this resolved? Let me know so I can close the issue....

**Comment by albertyckwok** [comment]
@tmcginn - it still doesn't work but feel free to close it. I will keep a private copy of the update for my own use. Let me know if you know or know someone who might know how to get permission to push the changes. The following is what I did and get:

**Comment by tmcginn** [comment]
I should be able to push it - can you let me know what you'd like changed?

**Comment by albertyckwok** [comment]
Sent update to you on an email.
