### ISSUE TITLE
Lab 500: STEP 1: Install Fn Server on Your Virtual Machine

### ISSUE THREAD

**Issue by tkedziora** [oracle/learning-library#365]
Hi, 

After running command:
`sudo systemctl start docker`
I got error:
`Failed to start docker.service: Unit not found.`

Previous steps completed without errors.

Thanks

**Comment by derekoneil** [comment]
Thanks for opening this issue -- I've updated the lab guide with the new docker package to install from yum. Instead of `yum -y install docker` it is now `yum -y install docker-engine`.
