### ISSUE TITLE
Lab 500: STEP 3: Deploy the Function Locally

### ISSUE THREAD

**Issue by tkedziora** [oracle/learning-library#366]
After running:
`fn deploy --app imgconvert --local`
an error occurs:
`Fn: app imgconvert not found`.

Previous steps completed without errors.

**Comment by derekoneil** [comment]
Fn now requires the `--create-app` flag for this operation. I updated the lab guide yesterday to add the flag, please refresh the page to see the changes. https://github.com/oracle/learning-library/commit/0ed04f8865b58970876e58264653e76e15158b5d
