### ISSUE TITLE
HOL Autonomous Data Warehouse - ORA-12514 TNS:listener issue

### ISSUE THREAD

**Issue by wcheng230** [oracle/learning-library#372]
In Practice 7: Login to the ADW database and store the object store credentials

Step 3. 
SQLDeveloper returns the following error: 
Status : Failure -Test failed: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
 
I download the connection wallet according to Practice 4. 
Not sure why the connection failed. 
SQLDeveloper 18.4.0 use the "Cloud Wallet" as the connection type rather than "Cloud PDB" as suggested in Practice 7 step 2. 

Anyone have seen this issue? Any advice? Thanks.
Wil

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
