### ISSUE TITLE
bike-share-prediction: script to create  STATION_STATUS_WEATHER and STATION_INFO

### ISSUE THREAD

**Issue by corradodebari** [oracle/learning-library#383]
HI. 
In bike-share-prediction I haven't found sql scripts to create tables STATION_STATUS_WEATHER and STATION_INFO, but only one to split them in training, validation and prediction. 
Thanks,
Corrado

**Comment by tmcginn** [comment]
@jwcho1221 - are you working on this lab? Can you respond to this issue please?

**Comment by tmcginn** [comment]
Closing this issue due to it's age. Please reopen it if this is still an issue.

**Comment by jwcho1221** [comment]
Hi Tom, 

As I replied to you on another email thread, I didn’t work on bike-share-prediction workshop. 


Thank you,
Joowon Cho | Cloud Engineer - Enterprise | Office: +1.737.867.3429, Mobile: +1.737.346.9429
Oracle North America Cloud Engineering  – 2300 Cloud Way, Austin, Texas 78741
