### ISSUE TITLE
Unable to delete LPG after associating with empty route table

### ISSUE THREAD

**Issue by gbouras** [oracle/learning-library#393]
LPG was created and assigned an empty route table. 
Created Separate Compartment
Created VCN without associated resources
Created Subnet
Created Route with no entries in table
Created LPG
Associated Empty Route Table
When trying to delete the LPG I get:

> Gateway entity ocid1.localpeeringgateway.oc1.phx.aaaaaaaan46s6wsezdg7mlmieg42ouwmfi5nbw5n3qpwynq45e5agstb3tkq using the route table exists

When trying to delete the route table I get the error message that it's associated with the LPG.

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
