### ISSUE TITLE
Problem with the Oracle Machine Learning plateform

### ISSUE THREAD

**Issue by PaulPeterECE** [oracle/learning-library#399]
Hi,

This morning, I've been trying to execute simple requests like a drop table (on a 20k lines table) or a create table on Oracle Machine Learning, but the request is pending forever and never succeeds. When I execute the same request on SQL Developer it takes 1s and it's successful.
I'm working on AZERELLI account.
Does the problem come from the OML interface or is it something else ? And how can I fix it ?

**Comment by dfsandoval91** [comment]
Hi, team,

I'm having the same issue, specifically when running %sql sentences. Is there any way to check the issues?

Thank you

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
