### ISSUE TITLE
Unable to Get Traefik Public IP

### ISSUE THREAD

**Issue by sachinshinde2512** [oracle/learning-library#404]
cat << EOF | kubectl apply -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-pathrouting-1
  namespace: sample-domain1-ns
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-domain1-cluster-cluster-1
          servicePort: 8001
      - path: /console
        backend:
          serviceName: sample-domain1-admin-server
          servicePort: 7001          
EOF

====================================================
$ kubectl describe svc traefik-operator --namespace traefik
Name:                     traefik-operator
Namespace:                traefik
Labels:                   app=traefik
                          chart=traefik-1.66.0
                          heritage=Tiller
                          release=traefik-operator
Annotations:              <none>
Selector:                 app=traefik,release=traefik-operator
Type:                     NodePort
IP:                       10.96.209.241
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30305/TCP
Endpoints:                10.244.2.3:80
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  30443/TCP
Endpoints:                10.244.2.3:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

**Comment by tmcginn** [comment]
Do you have an issue? If so, please let us know. Closing this issue for now.
