### ISSUE TITLE
Identify lab matrials

### ISSUE THREAD

**Issue by paulvi** [oracle/learning-library#407]
I got materials as on screenshot and link https://go.oracle.com/LP=78427.  
And as network is not so quick, I'd like to do at home later and attend more sessions during Oracle Code.

Are these all 5 labs pdf related to this repository?

<img width="791" alt="Screen Shot 2019-04-16 at 2 12 12 PM" src="https://user-images.githubusercontent.com/1614482/56186497-1a84b400-6052-11e9-9348-94b104acf638.png">

**Comment by tmcginn** [comment]
Yes: https://github.com/oracle/learning-library/tree/master/workshops/container-native-development-with-oke
