### ISSUE TITLE
LAB 100 error: create a simple sub-set of the lineorder data

### ISSUE THREAD

**Issue by Shadiat** [oracle/learning-library#413]
when I ran:

begin
--
dbms_scheduler.create_job( 
job_name => 'load_data',
job_type => 'PLSQL_BLOCK',
job_action => 'begin ' ||
' execute immediate ''create table lineorder_100m as select * from ssb.lineorder sample(1.66667)''; ' ||
' execute immediate ''create table customer as select * from ssb.customer where c_custkey in (select lo_custkey from lineorder_100m)''; ' ||
' execute immediate ''create table part as select * from ssb.part where p_partkey in (select lo_partkey from lineorder_100m)''; ' ||
' execute immediate ''create table supplier as select * from ssb.supplier where s_suppkey in (select lo_suppkey from lineorder_100m)''; ' ||
' execute immediate ''create table dwdate as select * from ssb.dwdate''; ' ||
' execute immediate ''grant select any table to public''; ' ||
'end;',
enabled => true );
end;
/  

PL/SQL created successfully showed.

But once, I did this in SQL developer: select * from USER_SCHEDULER_JOBS;
select * from user_scheduler_job_run_details;

It gave me this error, and now I cannot move on: 
Error starting at line : 1 in command -
begin
--
dbms_scheduler.create_job( 
job_name => 'load_data',
job_type => 'PLSQL_BLOCK',
job_action => 'begin ' ||
' execute immediate ''create table lineorder_100m as select * from ssb.lineorder sample(1.66667)''; ' ||
' execute immediate ''create table customer as select * from ssb.customer where c_custkey in (select lo_custkey from lineorder_100m)''; ' ||
' execute immediate ''create table part as select * from ssb.part where p_partkey in (select lo_partkey from lineorder_100m)''; ' ||
' execute immediate ''create table supplier as select * from ssb.supplier where s_suppkey in (select lo_suppkey from lineorder_100m)''; ' ||
' execute immediate ''create table dwdate as select * from ssb.dwdate''; ' ||
' execute immediate ''grant select any table to public''; ' ||
'end;',
enabled => true );
end;
Error report -
ORA-27477: "ADMIN"."LOAD_DATA" already exists
ORA-06512: at "SYS.DBMS_ISCHED", line 175
ORA-06512: at "SYS.DBMS_SCHEDULER", line 288
ORA-06512: at line 3
27477. 00000 -  "\"%s\".\"%s\" already exists"
*Cause:    An attempt was made to create an object with a name that has
           already been used by another object in the same schema.
*Action:   Reissue the command using a different name or schema.

**Comment by tmcginn** [comment]
It appears you attempted to execute the create job twice.
If this is still an issue, please reopen it.
