### ISSUE TITLE
Issue with ATP Labs 

### ISSUE THREAD

**Issue by joshisid** [oracle/learning-library#432]
Hi, 

I have found that git repo's hosted under cloudsolutionshubs have all vanish breaking every single labs for ATP. Can you please resolve this urgently as I have been pushing the ATP labs and demo's as part of the Autonomous Drive and even the links from our ATP App Dev Docs follow the same labs 

e.g of one of the repo - https://github.com/cloudsolutionhubs/ATPJava.git

**Comment by tmcginn** [comment]
Hi @joshisid - can you provide more details? I'm not sure what you are looking for....

**Comment by tmcginn** [comment]
Hi @joshisid - please open a new issue or send me an e-mail if you still have questions. Thanks.
