### ISSUE TITLE
Extra / in code for file 

### ISSUE THREAD

**Issue by alxfirst** [oracle/learning-library#448]
In the current code there is an extra "/" which leads to the wrong URL being used, example - o/**/**costs.dat : 
file_uri_list =>'https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/oracsmemeahub/b/ADWCMLTest/o//costs.dat',

File with this error: https://oracle.github.io/learning-library/workshops/journey4-adwc/scripts/400/create_external_tables.txt

To resolve, remove the last / in this line: 
define base_URL='https://objectstorage.us-phoenix-1.oraclecloud.com/n/adwctraining/b/ADWCLab/o/'
or

**Comment by OracleJustin** [comment]
I've checked the file and it looks like it's been fixed by another commit. Please close @kaymalcolm. 

![Screen Shot 2020-01-27 at 3 49 25 PM](https://user-images.githubusercontent.com/56048601/73223924-9d2bbb00-411c-11ea-86ac-0570f235a87f.png)
