### ISSUE TITLE
ADW - Import a table using impdp, Datapump from Object Storage

### ISSUE THREAD

**Issue by BigDuy01** [oracle/learning-library#465]
In the ADW workshop Lab 4, Step 2: Makes sure that you are in /home/opc/oracle/instantclient_18_3

This does not make sense.  It doesn't explain what it's talking about.

**Comment by tmcginn** [comment]
Hi @BigDuy01, can you provide the title of the workshop so I can track this down?

**Comment by tmcginn** [comment]
Hi @BigDuy01 - I am closing this issue due to its age - please open a new one if you still have an issue.
