### ISSUE TITLE
Grafana OCI lab is not working

### ISSUE THREAD

**Issue by mgueury** [oracle/learning-library#479]
learning-library/oci-library/L100-LAB/Grafana/Compute Monitoring using Grafana.md 

1) there is not explanation how to open a port 3000 from internet access ?

sudo firewall-cmd --permanent --zone=public --add-port=3000/tcp
sudo firewall-cmd --reload
+ add a security rule

2) the creation of the OCI datasource in graphana

Save and test gives: Data source is not working.
Despite this, there are signs that something is working. (Ex: I can see the list of compartments)

**Comment by umairs123** [comment]
1- You dont need to add security list rule for the ssh command as its enabling port forwarding by connecting client to server first and then doing port forwarding. I have a note stating it.
2- If you installed grafana plugin per below commands then there shouldnt be an issue, can you please make some time avaialble and we can verify ? . This lab has been executed multiple times without any reported issues.
sudo grafana-cli plugins install oci-datasource

3. We now need to set execute permission on one of the files, Enter command:

sudo chmod 555 /var/lib/grafana/plugins/oci-datasource/dist/oci-plugin_linux_amd64

4. Start Grafana server, Enter Command: 
         
sudo systemctl start grafana-server

**Comment by mgueury** [comment]
Hi,

1) Sorry, for the port forwarding. I missed the step.
2) I did this before, and redid it to be sure. It did not change anything.
Is it possible that it does not work because we use a lot of compartments in the tenant and that 
the compute is a sub/sub compartment ? 
- If you want, if you send me a public key via email (look for me in Aria). I can add it to the machine and you can check yourself.
- And/or should I look a particular log file ? 

Thanks,

**Comment by umairs123** [comment]
Hi 
  The sub compartment shouldn't be an issue. Which step is not working, i.e are you able to install Grafana and add OCI plugin OR you do not see anything in monitoring side  ? 
Just to be sure you are using Qloudable platform to run the lab ? if you are using your own tenancy then you will need to add below IAM policy as well.
**allow group <GROUP_NAME> to read metrics in tenancy**
**allow group <GROUP_NAME> to read compartments in tenancy**

you can use this public key 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAA2W6Fr+GW/PDrHi0Lv/i569RZmCTlmrxA4WZMdKr0Z6Rz/o1vpeCRIva43MUZnU4UDaRJO07Mbm++Ew5UWcNBdg5ntMnIwgwrFhiv0igFDLoeOA+oIbS5eckeb2vGRYqBSiopDucK9LTCyBROBMS44mtN+KBKXtKFUAQqud7FHTCDkwXIqZmB18m8pDrdWLUYEQBDoLPRDeHNvTCOF4V9BHnCrnSAHbr+Y9FTHRkcZYfGRUp2uf1H5Uvjl9rEgNm1Afs4QwbOmNOjBAhG+lY+p/2ErdYXbR9hvkWCk2p0T0t9BeEJ/dOwEsV1FBGIzUFxvFRY55WJigGQ+EcXXVD user
