### ISSUE TITLE
OCI registry lab is using old docker package

### ISSUE THREAD

**Issue by mgueury** [oracle/learning-library#494]
In learning-library/oci-library/DevOps/Container_Registry/Container_Registry_HOL.md 

sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo**
sudo yum install docker-ce –y

should be probably

sudo yum install docker-engine –y

**Comment by tmcginn** [comment]
@flavio-santino - can you confirm and close this issue?

**Comment by tmcginn** [comment]
@umairs123 - can you take a look?

**Comment by vrcrush** [comment]
similar issue....

**Comment by tmcginn** [comment]
I believe this is fixed in this version of the workshop: https://apexapps.oracle.com/pls/apex/dbpm/r/livelabs/view-workshop?p180_id=590

Please reopen it if this is still an issue.
