### ISSUE TITLE
oci-library/DevOps/OCI CLI lab small issue

### ISSUE THREAD

**Issue by mgueury** [oracle/learning-library#508]
learning-library/blob/master/oci-library/DevOps/OCI_CLI/OCI_CLI_HOL.md

1) OCI command does not work

oci compute image list --compartment-id <your compartment OCID> --query 'data[?contains("display-name",Oracle-Linux-7.6-20)]|[0:1].["display-name",id]'

I guess a typo in the wiki

2) This one is difficult to run

oci compute instance launch --availability-domain <your AD name> --display-name demo-instance --image-id <ID from previous step> --subnet-id <subnet OCID> --shape VM.Standard.E2.1 --assign-public-ip true --metadata '{"ssh_authorized_keys": "<your public ssh key here>"}'

- VM.Standard.E2.1  did not exist in my tenant, I had to use VM.Standard2.1 
- "your AD name" is hard to find, I tried the OCID, the name, and it was finally wQhE:EU-FRANKFURT-1-AD-1
  An example would help.

Thanks

**Comment by tmcginn** [comment]
@flavio-santino - can you take a look?

**Comment by tmcginn** [comment]
Closing this issue, please reopen if needed.
