### ISSUE TITLE
Problem with my account oracle virtual dev workshop

### ISSUE THREAD

**Issue by venturio1256** [oracle/learning-library#617]
Followed the instruction. But cannot access to my services after successfully login in

**Comment by venturio1256** [comment]
after login I got this message:
You are not authorized to access the app. Contact your system administrator.

**Comment by snicholspa** [comment]
Hello, I recommend the following the step under the section "What should I do if I sign up for a Cloud Trial and I don't receive the Welcome email or have an issue logging into the cloud with your account?" within the link https://community.oracle.com/docs/DOC-1031229.
