### ISSUE TITLE
bad links in intelligent chatbots workshop

### ISSUE THREAD

**Issue by OracleJB** [oracle/learning-library#726]
in the readme of the intelligent chatbot workshop (https://github.com/oracle/learning-library/tree/master/workshops/intelligent-chatbots)

the link "GitHub Pages site" links to the "Container Native Development with OKE Workshop" webpage. It should link here: https://oracle.github.io/learning-library/workshops/intelligent-chatbots/

The "Workshop Overview" link also gives a 404 error

**Comment by snicholspa** [comment]
Thank you for the feedback.  We've fixed the links.
