### ISSUE TITLE
please dont use implicit date conversions!

### ISSUE THREAD

**Issue by shredder2003** [oracle/learning-library#825]
in all script here incorrect date translations:
a.last_reported >= '12-AUG-17'

please use instead it:
a.last_reported >= to_date('12-AUG-17','dd-mon-rr','nls_date_language=AMERICAN')

because this scripts doesnt work in another languages/locations.

Applicable to notebook script like 
-- Validation data
Create table SSW_V as SELECT a.last_reported, a.STATIONID, a.TIME_INT, a.WEEKDAY_INT, a.TOTALDOCKS, a.AVAILABLEBIKES, a.STATUSVALUE, a.ACTIVITY, a.TRUACTIVITY, a.NOAVAILABLEBIKES, a.NOAVAILABLEDOCKS, a.AVG_TEMP, a.MIN_TEMP, a.MAX_TEMP, a.AVG_DEWPOINT, a.WIND_SPEED, a.WIND_DIRECTION, a.WIND_PERCENT, b.BOROUGHCODE, b.REGION_ID
    FROM Admin.Station_Status_weather a, Admin.Station_Info b
    WHERE a.STATIONID = b.STATION_ID and a.last_reported >= '28-AUG-17' and a.last_reported < '31-AUG-17' ;

and so on.

**Comment by aorcl** [comment]
Which of the labs was it?

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
