### ISSUE TITLE
Admin Console Not Found

### ISSUE THREAD

**Issue by zalkaf** [oracle/learning-library#852]
I followed all the steps in lab 100, 200, 300 successfully in: https://oracle.github.io/learning-library/workshops/wls-oke/?sourceType=%3Aow%3Alp%3A2t%3A%3ARC_NAMK180921P00075%3AWLSonPrem_HOL&intcmp=%3Aow%3Alp%3A2t%3A%3ARC_NAMK180921P00075%3AWLSonPrem_HOL&elqTrackId=935f30088fd042a582466517fa78da52&elqaid=77916&elqat=2&source=%3Aow%3Alp%3Acpo%3A%3A&page=LabGuide300.md

When I get to end of step 5, and try to open the admin server console from my browser, I'm getting page not found. Can you please advise?

**Comment by Sasankaa** [comment]
Try lab300: step 3 with below helm code snippet and continue from step 3.
Thanks!

helm install stable/traefik \
  --name traefik-operator \
  --namespace traefik \
  --values weblogic-kubernetes-operator/kubernetes/samples/charts/traefik/values.yaml  \
  --set "kubernetes.namespaces={traefik}" \
  --set "serviceType=LoadBalancer"

**Comment by zalkaf** [comment]
Yes I tried that. I got the external IP address, however, it's not accessible

**Comment by Sasankaa** [comment]
URL should be http://EXTERNAL-IP/console right?

**Comment by Sasankaa** [comment]
Also, check logs if there is any issue you can find. You may use either ./kubectl proxy to find any issues regarding your image or any other issues.

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
