### ISSUE TITLE
Introduction to Python Development with ATP - Fixes 

### ISSUE THREAD

**Issue by leahsbracken** [oracle/learning-library#878]
**Went through the entire lab and found a few errors detailed in this word doc.** 

**Link to lab**: https://oracle.github.io/learning-library/workshops/python4atp/?page=LabGuide050.md&sourceType=%3Aow%3Alp%3Acpo%3A%3ARC_NAMK190418P00033%3AHOLPythonATP&intcmp=%3Aow%3Alp%3Acpo%3A%3ARC_NAMK190418P00033%3AHOLPythonATP&elqTrackId=e70b90380dd74d3fb67f7045b56edc6a&elqaid=83886&elqat=2&source=%3Aow%3Alp%3Acpo%3A%3A
[Introduction to Python Development with Autonomous Transaction Processing.docx](https://github.com/oracle/learning-library/files/3762505/Introduction.to.Python.Development.with.Autonomous.Transaction.Processing.docx)

**Comment by tmcginn** [comment]
@kaymalcolm - can you confirm these finding were corrected in the workshop? Thanks

**Comment by kaymalcolm** [comment]
This can be closed.  This was moved to a new location by Leah.
