### ISSUE TITLE
Create OKE Cluster: invalid token version

### ISSUE THREAD

**Issue by XiaoYu-HN** [oracle/learning-library#963]
follow the guide of OCI Level 200 Lab: Terraform and Oracle Cloud Infrastructure, when I use terraform to create OKE cluster, below error occured:
```
data.oci_containerengine_cluster_kube_config.test_cluster_kube_config: Refreshing state...
oci_containerengine_node_pool.node_pool1: Creating...
oci_containerengine_node_pool.node_pool1: Creation complete after 2s [id=ocid1.nodepool.oc1.eu-frankfurt-1.aaaaaaaaaftdqnzrmfqtozrygbqtgzjqga4tiyzumvtgenzygn4dmzdgmu2d]

Error: Service error:InvalidParameter. invalid token version.. http status code: 400. Opc request id: 62772a00e50b825439154bb159100dad/BD53D6C0418B4C278A7CB273147E26F7/763D08E014DE4BD7B5CD2EB419B90BFB

  on kubeconfig.tf line 9, in data "oci_containerengine_cluster_kube_config" "test_cluster_kube_config":
   9: data "oci_containerengine_cluster_kube_config" "test_cluster_kube_config" {

```

actually, the cluster is created, and doesn't affect remaining Lab, but I must manually delete resource in OCI console, if i use `terraform destroy` to cleanup, the same error occured.

**Comment by jkremser** [comment]
workaround:

```
terraform state rm module.oke.oci_containerengine_cluster.k8s_cluster
terraform refresh
```

**Comment by RobertoMagalhaes** [comment]
Unfortunately,, For me, that solution does not work ...
if you can help me ,,,,  


`oci_core_subnet.s-lb2: Refreshing state... [id=ocid1.subnet.oc1.iad.aaaaaaaaototiiksyrj3kuasesdg3bca]
oci_core_subnet.s-w2: Refreshing state... [id=ocid1.subnet.oc1.iad.aaaaaaaan3euc2seefpl2raabks6xea]
oci_containerengine_cluster.oke_cluster: Refreshing state... [id=ocid1.cluster.oc1.iad.aaaaaaaaafstaasddmzstgyldmc3dsmbumnrg]
data.oci_containerengine_cluster_kube_config.test_cluster_kube_config: Refreshing state...

Error: Service error:InvalidParameter. invalid token version.. http status code: 400. Opc request id: 2e80c36dc5340dssab49b9e7f4/2F0841B82ssa4D56/2BDA5D305FBF4F18AE4917asD4

  on kubeconfig.tf line 9, in data "oci_containerengine_cluster_kube_config" "test_cluster_kube_config":
   9: data "oci_containerengine_cluster_kube_config" "test_cluster_kube_config" {
`



att

**Comment by tmcginn** [comment]
Hello, I am closing this issue due to its age. If this is still an issue, please reopen it.
